configuration: Release

os: Visual Studio 2015 RC

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

build:
  parallel: true

clone_depth: 1

deploy:
- provider: NuGet
  api_key:
    secure: /Aez/maYDiX55BgGX9EkbhXBaBySsfdKifgB9SZxqySOrwtMVgPf7jOwS2XwKYJR
  skip_symbols: true
  on:
    branch: master